cta-observatory/magic-cta-pipe

magicctapipe/image/cleaning.py

In the case that bad/hot pixels treatment is used, the original calibrated image was overwritten during the cleaning. Now the behavior is consistent if the pixel treatment is used or not.

Add copy of image so that the original one is not overwritten.

---

magicctapipe/scripts/lst1_magic/config.yaml
magicctapipe/scripts/lst1_magic/lst1_magic_mc_dl0_to_dl1.py

This pull request changes the extractor type from the LocalPeakWindowSum to SlidingWindowMaxSum which is used in MARS analyses, and disables the integration correction. Also, a correction factor is applied to DL1 images which is derived from the difference of the conversion factors 1.165 (= 0.0155/0.0133) between MARS and simtel.

Fix magic calibration

---

magicctapipe/config/magic-cta-pipe_config_stereo.yaml
magicctapipe/scripts/magic/magic_calibrated_to_dl1.py

a few of the variable names had to be updated, and some of the imports are now from different files
@aleberti - I'm not sure if this script is still useful, if not we should simply remove it. 
nevertheless I saw similar problems in other files. Also the config files need to be updated, but I was not sure which one is used by which script, hence I did not modify them in this PR

fixed the script so it works with the current version

---

magicctapipe/scripts/lst1_magic/lst1_magic_stereo_reco.py

is_valid is cast to int (from bool) before writing it out, otherwise pytables complains when writing the file.

Cast is_valid to int before writing it out.

---

magicctapipe/scripts/lst1_magic/lst1_magic_mc_dl0_to_dl1.py

the regular expression expected run number then _ and arbitrary text followed with .simtel.gz
but LSTProd2 files have e.g. run999.simtel.gz.
Now the regular expression wants either . or _ after the run number, arbitrary (possibly empty) text and simtel.gz
I checked that it works on the lstprod "train" files, and on the original @YoshikiOhtani proton files (the gamma files of @YoshikiOhtani are using a separate regex)

modified dl0_to_dl1 script to allow processing files with file names following LSTProd2 style

---

magicctapipe/image/muons/muon_analysis.py
magicctapipe/scripts/lst1_magic/config.yaml
magicctapipe/scripts/lst1_magic/lst1_magic_mc_dl0_to_dl1.py
magicctapipe/scripts/lst1_magic/muon_analysis_LST_or_MAGIC_data.py

Modified the analysis function to work in this case and added a dedicated script.
Related to #19

Add muon analysis on calibrated data

---

magicctapipe/scripts/lst1_magic/config.yaml
magicctapipe/scripts/lst1_magic/lst1_magic_create_irf.py

This PR adds minimum and maximum values for the theta2 and gammaness cuts.

Add minimum and maximum values for theta2 and gammaness cuts.

---

setup.py

It just sets the same version of ctapipe_io_magic in setup.py as environment.yaml.

Updated the ctapipe_io_magic version in setpy.py

---

magicctapipe/reco/estimators.py
magicctapipe/scripts/lst1_magic/config.yaml
magicctapipe/scripts/lst1_magic/lst1_magic_create_irf.py
magicctapipe/scripts/lst1_magic/lst1_magic_dl2_to_dl3.py
magicctapipe/utils/functions.py

It is still a draft pull request related to the issue #69.

Change the definition of the DL2 parameter uncertainty

---

magicctapipe/image/muons/muon_analysis.py
magicctapipe/scripts/lst1_magic/lst1_magic_mc_dl0_to_dl1.py
magicctapipe/utils/__init__.py
magicctapipe/utils/functions.py

In the pull request #72 there was a confusion related to the event source which is created several times in the MC DL0 to DL1 script. This actually could make confusions again in the future when we adapt the script to the cta-process tool. Then by looking into the script I found that it is not absolutely necessary and could be more simplified. So with this pull request I refactored the code by creating the event source only once, and also with the following minor changes:
- use the CameraFrames stored in `subarray.tel[tel_id].camera.geometry.frame` instead of creating them inside the script
- modified the muon analysis modules so as not to keep the telescope names, because now in the standard analysis the name is not used
- modified the logger information display to improve the …

Refactor MC DL0 to DL1 script

---

magicctapipe/scripts/lst1_magic/lst1_magic_stereo_reco.py

This pull request includes some minor refactoring of the code of the stereo parameters reconstruction. Here is a brief summary of the changes:
- changed the option name of the function `stereo_reconstruction` from `magic_only` to `magic_only_analysis` (but the argument name `--magic-only` used when running the script does not change).
- cleaned up the code of checking the angular distance of the pointing directions
- modified the logger information display
I checked that the outputs do not change before and after the refactoring and so it would be safe to merge now, but again I keep it here a few days so any comments or requests are very welcome.

Refactor stereo reconstruction

---

magicctapipe/reco/estimators.py
magicctapipe/scripts/lst1_magic/config.yaml
magicctapipe/scripts/lst1_magic/lst1_magic_dl1_stereo_to_dl2.py
magicctapipe/scripts/lst1_magic/lst1_magic_train_rfs.py

The main purpose of this pull request was to implement an option to use unsigned features for training/applying RFs, but at the same time I refactored the code a bit. Here is a briefly summary of the changes that I did:
- Added the option "--use-unsigned" with which unsigned features are used for training and applying RFs.
- Drop NaN values from an input data frame inside the estimator modules, instead of doing it in the load functions.
- Use the CameraFrame stored in a subarray instead of creating it inside the DirectionEstimator
- Changed the argument name of lst1_magic_dl1_stereo_to_dl1.py, from `--input-file` to `--input-file-dl1`
- Changed the logger information display
Any comments are very welcome.

Refactor training/applying RFs 

---

environment.yml

Installing the software in my local Mac OS failed due to a problem of installing protozfits with pip. It was solved by installing the module with conda before installing lstchain with pip. Also, I cleaned up the environment.yml file a bit as follows:
- Remove the cta-observatory channel and instead add conda-forge channel, and then clean some lines
- Install uproot with conda instead of pip, because it is available from conda-forge
I think this changes do not harm installations for other systems. I wanted to try it just in case for linux, but now the IT container is not accessible..  I assign @aleberti for a reviewer so it would be great if you could have a look at them and merge this if it is OK for you. Thanks!

Fix the problem of installing the software with a Max OS

---

magicctapipe/scripts/lst1_magic/README.md

Thanks @aleberti for adding the README. For the MAGIC-only analysis, one needs only `--magic-only` argument when running stereo reconstruction so I added the explanation about this. Also, I found a typo so I corrected it.

Fix README for the combined analysis scripts

---

magicctapipe/scripts/lst1_magic/config.yaml
magicctapipe/scripts/lst1_magic/lst1_magic_create_irf.py
magicctapipe/scripts/lst1_magic/lst1_magic_dl2_to_dl3.py
magicctapipe/utils/__init__.py
magicctapipe/utils/functions.py

this still does not work too good. I will check if there is no problem with interpolation. Nevertheless @YoshikiOhtani any feedback on the code is very much appreciated.

Implement IRF interpolation method

---

magicctapipe/scripts/lst1_magic/lst1_magic_stereo_reco.py

This pull request fixes the critical issue #92 happened when reconstructing any2 tel events, which used the Hillas parameters of the previous event by mistake. Now the ArrayEventContainer is initialized every time inside the event loop, so the previous event information is safely cleaned. This closes #92.

Fix the stereo reconstruction for any 2 tel events

---

magicctapipe/scripts/lst1_magic/lst1_magic_mc_dl0_to_dl1.py

It is already fixed in the open pull request #91, but for people whose use the master branch, let me fix also the master branch. There is an issue on the regex to read the primary ID of a MC file for proton and helium.

Fix the regex to get the primary ID

---

environment.yml
setup.py

This pull request updates the required version of ctapipe_io_magic from v0.4.5 to v0.4.6, which is adapted for MAGIC-mono real data.

Update the required version of ctapipe_io_magic

---

magicctapipe/scripts/lst1_magic/lst1_magic_dl2_to_dl3.py

This pull request fixes the issue #94 about the interpolation of the energy dispersion. With this solution the renormalization is performed along the migration axis. I confirm that this fix works for my Crab samples.

Fix the issue of energy dispersion interpolation

---

magicctapipe/io/io.py
magicctapipe/scripts/lst1_magic/lst1_magic_dl1_stereo_to_dl2.py
magicctapipe/scripts/lst1_magic/lst1_magic_stereo_reco.py

This pull request removes the unnecessary for loop in the `magicctapipe.io. save_pandas_data_in_table` function. It also changes the argument name from `data` to `input_data`, and adapts the scripts to use the new name.

Remove unnecessary for loop in `save_pandas_data_in_table`

---

magicctapipe/io/gadf.py
magicctapipe/io/io.py

1) tel_combo was read as a float but used a index, and required cast to int this is a bit dangerous but it seems to be only used for the metadata 
2) list of telescopes was passed as an array, but instead should be a string
@YoshikiOhtani can you have a look?
the first problem actually would be better to be solved already earlier: saving those combinations as int and not float

fixed two problems that prevented DL3 generation

---

magicctapipe/scripts/lst1_magic/magic_calib_to_dl1.py
setup.py

This PR updates the treatment of MAGIC MC data, since there are bad pixels (pixel 0, a know feature of MAGIC simulation) and hot pixels (outliers in charge). For this, `ctapipe-io-magic` version has been updated.
Also, now mono and SumT data are fully supported. For the latter, MaTaJu cleaning implementation is still missing, so a warning is thrown.

Update magic mc treatment

---

environment.yml
magicctapipe/scripts/lst1_magic/magic_calib_to_dl1.py

This pull request removes the `--allow-mono` option from the script `magic_calib_to_dl1.py`. It was introduced not to process the mono-trigger data unexpectedly, since we do not know the trigger settings from file names, but I found another way to remove them so it is not needed now. @aleberti just in case, does this change affect the pull request about the Hillas image comparison?

Remove the allow mono trigger option

---

magicctapipe/scripts/lst1_magic/merge_hdf_files.py

With this pull request I changed the functionality of the `merge_hdu_files.py` script when the `--subrun-wise` option is used. Originally, even if either M1 or M2 subrun file of a given subrun ID is missing, the script processes the file and changed its name as if both M1 and M2 files exist. Here is the example of what I meant:
> data/dl1/dl1_M1.Run05096367.011.h5
> data/dl1/dl1_M2.Run05096367.011.h5
> --> Output file: data/dl1/merged/dl1_MAGIC.Run05096367.011.h5
> 
> data/dl1/dl1_M1.Run05096367.012.h5
> --> Output file: data/dl1/merged/dl1_MAGIC.Run05096367.012.h5
Now, with this script the subrun ID that either M1 or M2 subrun file is missing is skipped. If one wants to merge the file, either `--run-wise` option or simply running without any options can be used.

Merge only the subrun files that both M1 and M2 exist

---

magicctapipe/io/io.py

Sorry but I realized that the pull request #103 did not solve the problem of creating an event list HDU. The type of `combo_type` is indeed converted to int in `get_stereo_events`, but it is again converted to float in `get_dl2_mean`, where the mean of `combo_type` is calculated and it automatically changes its type. With this pull request I added a line to reconvert it (and in addition `multiplicity`) to int, and it finally fixed the problem.

Fix the issue when creating an event list HDU

---

magicctapipe/io/io.py
magicctapipe/scripts/lst1_magic/lst1_magic_event_coincidence.py

With this pull request we keep the MAGIC-stereo events non-coincident with any LST-1 mono events. Since they do not have LST observation/event IDs, the MAGIC IDs are assigned for the `obs_id` and `event_id` variables. It closes #108.
**(EDIT)** It is based on another pull request #109 which should be merged to the master at first.

Keep non-coincident MAGIC-stereo events

---

magicctapipe/scripts/lst1_magic/lst1_magic_event_coincidence.py

I'm sorry but the pull request #109, which is already merged to the master branch, introduced a critical bug in the event coincidence search. I realized that it extracted completely wrong LST-1 events as coincident events (by wrongly selected indices `indices_lst`), so with this pull request I fix the issue. Also, I added the missing code to assign LST observation and event IDs to coincident MAGIC events, as the MAGIC IDs are assigned to coincident LST-1 events.

Fix an issue that wrong LST-1 events are extracted as coincident events

---

magicctapipe/scripts/lst1_magic/lst1_magic_event_coincidence.py

With this pull request I introduced a skip if any coincident events are found in all time offsets. It sometimes happen that an input LST-1 data have only a small number of events, and in that case the script crashed with a bit unclear error message.

Skip the event coincidence if no coincident events are found

---

magicctapipe/io/io.py
magicctapipe/scripts/lst1_magic/lst1_magic_create_irf.py

I realized that with the pull request #99 I forgot to add the IRF observation time, which is used for creating a background model, to the extra header, so let me do so with this pull request.

Add IRF observation time to the header

---

magicctapipe/io/io.py

With this pull request let me drop the MAGIC events whose observation and event IDs are duplicated, which sometimes happen at the DL1 level and might affect the coincidence search.

Drop the MAGIC events that observation and event IDs are duplicated

---

environment.yml
setup.py

With this pull request I updated the python version to 3.8 to use a new feature, and accordingly other packages. Removing the requirement on `bokeh` is needed to update the python version, and regarding `sphinx` I just let it follow the requirement of the other packages. For the other packages I just updated the versions. @aleberti could you please have a look? Thanks in advance.

Update the python version and some other packages

---

magicctapipe/scripts/lst1_magic/config.yaml

After updating the magic-cta-pipe environment a new version of scikit-learn (v1.1.2) is installed, which is OK because we do not specify any requirements to that module. However there is a future warning appeared during training RFs that the `max_features = "auto"` is deprecated. For RF regressors the "auto" means that all the features are considered at each split, and for RF classifiers  the `sqrt(n_features)` is used. It suggested to use them explicitly, so I changed the default settings as follows. Now the `max_features = 1.0` is used for RF regressors, which in case of float the `n_features * max_features` is used, so the setting is actually not changed.

Change the default settings of `max_features`

---

magicctapipe/scripts/lst1_magic/lst1_magic_dl2_to_dl3.py

This pull request fixes the issue that the full-enclosure IRFs are not interpolated properly if the number of input IRF files is just one.

Fix the issue for the interpolation of the full-enclosure IRFs

---

magicctapipe/scripts/lst1_magic/merge_hdf_files.py

modified slightly the script for merging the files to allow to merge again files that were already merged. I.e. to merge run1_to_100, run_101_to_200, run_201_to_300 into run1_to_300. I checked (on MC dl1 files) that it does not break the regular  behavior) and on merged dl2 files that it works. 
One small issue is that if you merge e.g. 1_to_1000 and 2000_to_3000 it will stay say 1_to_3000 even if it does not have all the runs in between, which might be in some occasions misleading, however this was already happening before and it is also possible to have a run missing

allow to further merge already merged files

---

magicctapipe/scripts/lst1_magic/config.yaml

for all the RFs: g/h separation, energy and direction

added pointing altitude and azimuth as the parameters for the training

---

.github/workflows/ci.yml
magicctapipe/io/io.py

Exception handling (event type) in `load_dl2-data_file`. Mamba instead of conda in CI (with conda, workflows fail and dependencies can't be installed)

Load dl2 data exc

---

magicctapipe/scripts/lst1_magic/config.yaml
magicctapipe/scripts/lst1_magic/lst1_magic_event_coincidence.py

Since the time offset depends on the observation dates, we needed to tune the offset scan region if we use the current method. This PR adds an option (`all_combination`) to select the best time offset among all possible combinations using large shower events. For the moment, 50 (MAGIC) x 50 (LST) events are selected by default to compute all possible time offsets and count coincident events with an assumed offset.

Update coincident event search using large shower events

---

magicctapipe/io/io.py
magicctapipe/scripts/lst1_magic/config.yaml
magicctapipe/scripts/lst1_magic/lst1_magic_dl2_to_dl3.py

changes for source path interpolation:
- added a possibility to use node up to a given distance from the data (this is useful to select only the nodes on the raising or falling part of the source path)
- allowed two interpolation schemes cosZdAz - like it was before, and cosZd (in which the interpolation is done only over cosZd, but normally you would select with the option above the nodes with similar azimuth)

Zenith interpol

---

magicctapipe/io/io.py

this is used in the computation of the dead time, but the output is also stored in DL3 index file since load_dl2_data is normally run with a quality cut in disp_diff its rate of events is much smaller, and cutting everything >0.1 s removes a lot of real ontime (~40%). This does not have affect the spectra (probably), because gammapy is recomputing the ontime, but still produces a very confusing information inside the DL3 index files 1s should be small enough to remove real gaps.

changed the gap size from 0.1s to 1 s

---

magicctapipe/scripts/lst1_magic/config.yaml
magicctapipe/scripts/lst1_magic/lst1_magic_event_coincidence.py

After WRS re-synchronization, the time offset between LST-1 and MAGIC was changed to -6.2 us.
This PR just updated the history comment in the script and config file.

Update the history of the time offset between LST-1 and MAGIC

---

README.rst

Following https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge. The badge was showing "failing" even if the CI was succesfull.

Update CI badge according to latest practices.

---

.github/workflows/ci.yml

I realized that despite the name of the branch was wrong in the `pre-commit` command, it was passing anyway. Now corrected the name to `master`.

Correct name of branch for pre-commit workflow.

---

Makefile
docs/developer-guide/getting-started.rst
docs/developer-guide/pull-requests.rst

Add in the documentation practices before opening a PR or before committing changes to an already open PR

Docs before pull request

---

.pre-commit-config.yaml
docs/conf.py
docs/developer-guide/getting-started.rst
magicctapipe/image/calib.py
magicctapipe/image/cleaning.py
magicctapipe/image/leakage.py
magicctapipe/image/muons/muon_analysis.py
magicctapipe/io/containers.py
magicctapipe/io/gadf.py
magicctapipe/io/io.py
magicctapipe/reco/estimators.py
magicctapipe/scripts/lst1_magic/create_dl3_index_files.py
magicctapipe/scripts/lst1_magic/lst1_magic_create_irf.py
magicctapipe/scripts/lst1_magic/lst1_magic_dl1_stereo_to_dl2.py
magicctapipe/scripts/lst1_magic/lst1_magic_dl2_to_dl3.py
magicctapipe/scripts/lst1_magic/lst1_magic_event_coincidence.py
magicctapipe/scripts/lst1_magic/lst1_magic_mc_dl0_to_dl1.py
magicctapipe/scripts/lst1_magic/lst1_magic_mc_muon_analysis.py
magicctapipe/scripts/lst1_magic/lst1_magic_stereo_reco.py
magicctapipe/scripts/lst1_magic/lst1_magic_train_rfs.py
magicctapipe/scripts/lst1_magic/magic_calib_to_dl1.py
magicctapipe/scripts/lst1_magic/merge_hdf_files.py
magicctapipe/scripts/lst1_magic/muon_analysis_LST_or_MAGIC_data.py
magicctapipe/scripts/mars/effective_area_melibea.py
magicctapipe/scripts/mars/mars_images_to_hdf5.py
magicctapipe/utils/badpixels.py
magicctapipe/utils/camera_geometry.py
magicctapipe/utils/functions.py
magicctapipe/utils/gti.py
pyproject.toml

Add validation of the numpydoc documentation in pre-commit and during documentation building.

Add numpydoc validation

---

docs/api-reference/scripts/index.rst

Add the scripts module to the documentation.

---

magicctapipe/scripts/lst1_magic/config.yaml
magicctapipe/scripts/lst1_magic/lst1_magic_event_coincidence.py

After the power cut and WRS synchronization, the time offset between MAGIC and LST1 was changed: -1583.8 us on Nov 15, 118.8 us since Nov 16.

Update time offset history

---

magicctapipe/scripts/lst1_magic/create_dl3_index_files.py

after removing the old copied lstchain code for creating those index files and using the current (lstchain 0.10) code instead the script stoped working because of a small change of API in the function. Note that since the function is taken from lstchain, in the header file of the output index files 'lstchain' will be written as the creation program
@aleberti or  @Elisa-Visentin, please have a quick look and if you are fine with those changes we merge them into the "lstchain" branch

fix to create HDU and OBS index files with lstchain0.10

---

README.rst
docs/index.rst

Add a note that depending on the LST-1 data to analyze, different versions of MCP need to be used due to the incompatible versions of the subarray, camera and optics tables saved in the Subarray object by ctapipe v0.12 and v0.19.

Add in README a note about different LST-1 data and MCP versions.

---

.github/workflows/ci.yml
docs/conf.py

Fixes the running of tests by adding single quotes when getting secrets, which avoids that special characters are wrongly interpreted. Also fixes documentation with the new URL for the iminuit documentation, now moved to https://scikit-hep.org/iminuit/.

Fix tests docs

---

.github/workflows/ci.yml
magicctapipe/conftest.py
magicctapipe/scripts/lst1_magic/lst1_magic_stereo_reco.py

Catch the numpy LinAlgError when recostructing the stereo parameters.

---

magicctapipe/conftest.py

I noticed that train and test files for gamma and protons are different between my machine and the ones of the CI. The `glob` function returns files not in particular order (e.g. alphabetical), but according to `ls -U`. This can change system by system. That is why sometimes they fail and sometimes they pass. Now I apply a sorting, and assign train and test as in my machine, where the tests pass.

Sort files and assign train and test files.

---

magicctapipe/scripts/lst1_magic/lst1_magic_mc_dl0_to_dl1.py

Remove averaging of positions in MCs.

---

.github/workflows/ci.yml

Fixes the issue with codecov reports not uploaded as reported in latest actions.

Add codecov token to upload reports.

---

magicctapipe/scripts/lst1_magic/semi_automatic_scripts/__init__.py
magicctapipe/scripts/lst1_magic/semi_automatic_scripts/clusters.py
magicctapipe/scripts/lst1_magic/semi_automatic_scripts/coincident_events.py
magicctapipe/scripts/lst1_magic/semi_automatic_scripts/merging_runs.py
magicctapipe/scripts/lst1_magic/semi_automatic_scripts/setting_up_config_and_dir.py

the generation of the script lines for SLURM was used in ~10 different places, and also sometimes it was not done properly, because the lines were merging, e.g.:
```
!/bin/sh
#SBATCH -p short
#SBATCH -J Crabtest
#SBATCH --array=0-12
#SBATCH -n 1
#SBATCH --output=/home/julian.sitarek/ws/analiza/autoMCP/20240508/out/v0.4.2.dev60+gc16368d.d20240405/Crabtest/DL1/M2/2023_11_19/5111122/logs/slurm-%x.%A_%a.out#SBATCH --error=/home/julian.sitarek/ws/ana
liza/autoMCP/20240508/out/v0.4.2.dev60+gc16368d.d20240405/Crabtest/DL1/M2/2023_11_19/5111122/logs/slurm-%x.%A_%a.err#SBATCH --mem 2g
ulimit -l unlimited
ulimit -s unlimited
ulimit -a
```
Now it is moved to a separate function where you can set most important parameters

Separating generation of the SLURM-specific lines 

---

magicctapipe/scripts/lst1_magic/semi_automatic_scripts/clusters.py
magicctapipe/scripts/lst1_magic/semi_automatic_scripts/coincident_events.py
magicctapipe/scripts/lst1_magic/semi_automatic_scripts/job_accounting.py
magicctapipe/scripts/lst1_magic/semi_automatic_scripts/merging_runs.py
magicctapipe/scripts/lst1_magic/semi_automatic_scripts/setting_up_config_and_dir.py

refactoring of merging_runs to unify the code for NSB_match yes/no
with some change of behaviour (the files to be run over are read from .txt files but the script is checking if the directories with the data exist)

Auto mcp errors coin

---

magicctapipe/scripts/lst1_magic/semi_automatic_scripts/job_accounting.py
magicctapipe/scripts/lst1_magic/semi_automatic_scripts/stereo_events.py

error management for stereoscopic reconstruction semi automatic script
this one is forked from auto_MCP_coincidence branch, so it is best to first merge #223 before merging this one

Auto mcp stereo

---

magicctapipe/io/io.py
magicctapipe/io/tests/test_io.py

the problem was that occasionally two LST-1 images could be assigned to the same MAGIC event. Now in case of such ambiguity both are removed. If there are too many such events >5 the program will exit with error code 11

fix for #224

---

magicctapipe/scripts/lst1_magic/semi_automatic_scripts/job_accounting.py

- it catches now a case when RSS memory is not available and returned as '0' (instead of much more common empty string)
- now from the config file we read also the source name and range of dates and check only directories that much those note that the other option with list of dates instead of range is still ignored
@joannaWojS this should fix the error that you experienced during checking DL1Coincidence outputs. Please let me know if everything is working fine

changes in job_accounting

---

magicctapipe/image/calib.py
magicctapipe/image/tests/test_calib.py
magicctapipe/resources/test_config_calib.yaml
magicctapipe/scripts/lst1_magic/config.yaml
magicctapipe/scripts/lst1_magic/lst1_magic_mc_dl0_to_dl1.py
magicctapipe/scripts/lst1_magic/tune_magic_nsb.py
setup.cfg

a script to derive the missing NSB noise in MAGIC part of the simulations and the modifications to the calibration to allow adding the noise also for MAGIC

Tune magic nsb

---

magicctapipe/scripts/lst1_magic/semi_automatic_scripts/job_accounting.py

it takes text outputs with return codes of running in the cluster, and updates the h5 database with the runs for the moment it only works with DL1/M[12] step

introduced updating of the database

---

magicctapipe/scripts/lst1_magic/semi_automatic_scripts/coincident_events.py
magicctapipe/scripts/lst1_magic/semi_automatic_scripts/config_auto_MCP.yaml
magicctapipe/scripts/lst1_magic/semi_automatic_scripts/merge_stereo.py
magicctapipe/scripts/lst1_magic/semi_automatic_scripts/merging_runs.py
magicctapipe/scripts/lst1_magic/semi_automatic_scripts/stereo_events.py

Add the possibility to use, for each step, input data processed with an older MCP version wrt the current one

In_out_versions

---

.pre-commit-config.yaml
magicctapipe/io/io.py

It sometimes happened that the IRF files have different bin ranges saved despite using the same input card. The difference is very small, comparable to the numerical accuracy of double precision. I saw it in the files processed in CNAF and my suspicion is that it comes from inhomogenuity of machines over which the code was run. Now if different binning is detected, it checks also if the relative difference exceeds somewhere 10^-15 and only then raises an error.

Fixed DL3 creation complaining about mismatch in binning.
