cta-observatory/magic-cta-pipe

- magicctapipe/scripts/lst1_magic_mc/make_irfs_MAGIC_LST.py
- magicctapipe/scripts/lst1_magic_mc/stereo_reco_MAGIC_LST.py
- magicctapipe/scripts/lst1_magic_mc/train_rfs_MAGIC_LST.py
- magicctapipe/utils/__init__.py
- magicctapipe/utils/utils.py
Please don't reimplement methods of builtin types
> Replace get_key_if_exists with dict.get

- .gitignore
- MANIFEST.in
- pyproject.toml
Setup to allow building the package to upload it to PyPI.
> Add files pypi

- environment.yml
- setup.cfg
- setup.py
Update dependency of ctapipe_io_magic
> Update magic reader dependency

- magicctapipe/scripts/lst1_magic/lst1_magic_dl1_to_dl2.py
- magicctapipe/scripts/lst1_magic/lst1_magic_stereo_reco.py
This pull request fixes a few issues of the combined analysis scripts.
> Fix the LST + MAGIC analysis scripts

- magicctapipe/image/cleaning.py
Add image clipping with default value at 750 phe.
> Add clipping of image

- magicctapipe/scripts/lst1_magic/lst1_magic_event_coincidence.py
This pull request includes a commit to the event coincidence script. It excludes interleaved pedestal/calibration events from the LST-1 data frame before searching for coincident events.
> Exclude interleaved events from the LST-1 data frame

- magicctapipe/image/__init__.py
- magicctapipe/image/cleaning.py
- magicctapipe/reco/stereo.py
- magicctapipe/scripts/performance/stereo_reco_MAGIC_LST.py
PR to fix stereo_reco_MAGIC_LST.py script as requested in #32. Closes #32.
> Fix stereo reco magic lst

- magicctapipe/scripts/lst1_magic/lst1_magic_create_irf.py
When applying the theta2 cuts, the operator >= was used. Fixed by using <= operator.
> Use "lower equal" operator when applying th2 cuts.

- magicctapipe/scripts/lst1_magic/merge_hdf_files.py
Just adds an optional argument to specify the output directory.
> Add output directory to merge_hdf_files.py

- magicctapipe/scripts/lst1_magic/config.yaml
- magicctapipe/scripts/lst1_magic/lst1_magic_create_irf.py
This pull request refactors the code of the `lst1_magic_create_irf.py` script a bit. There is no change of functionality, but the output file names are bit shortened such as "dynamic -> dyn" and "global -> glob".
> Refactor create_irf script

- environment.yml
- setup.py
Specification for ipython and ipykernel versions. Closes #42.
> Specify requirement for ipython and ipykernel

- magicctapipe/scripts/lst1_magic/lst1_magic_create_irf.py
- magicctapipe/scripts/lst1_magic/lst1_magic_dl1_stereo_to_dl2.py
- magicctapipe/scripts/lst1_magic/lst1_magic_dl2_to_dl3.py
- magicctapipe/scripts/lst1_magic/lst1_magic_event_coincidence.py
- magicctapipe/scripts/lst1_magic/lst1_magic_mc_dl0_to_dl1.py
- magicctapipe/scripts/lst1_magic/lst1_magic_stereo_reco.py
- magicctapipe/scripts/lst1_magic/magic_calib_to_dl1.py
- magicctapipe/scripts/lst1_magic/merge_hdf_files.py
As Julian faced some problems when processing the new AllSky MCs, with this pull request I removed `resolve()` used when getting the input file name. It closes #61. 
EDIT: @jsitarek I will merge this to the master so please pull it to your local at your convenience
> Removed resolve() when getting the input file name

- .pylintrc
This pull request just adds the pylint rc file used in ctapipe. Let me try to follow the suggestions and push some more commits to the pull requests which are still open for refactoring the codes.
> Add the pylint rc file used in ctapipe

- magicctapipe/scripts/lst1_magic/config.yaml
- magicctapipe/scripts/lst1_magic/lst1_magic_mc_dl0_to_dl1.py
- magicctapipe/scripts/lst1_magic/magic_calib_to_dl1.py
This pull request refactors the magic_calib_to_dl1.py script. Here is a brief summary of the changes:
- Use the CameraFrame stored in a subarray instead of creating it
- Modified the treatment of the `find_hotpixels` option
- Changed the logger information display
Any comments are very welcome.
> Refactor MAGIC Calib to DL1

- magicctapipe/scripts/lst1_magic/create_dl3_index_files.py
- magicctapipe/scripts/lst1_magic/merge_hdf_files.py
- magicctapipe/utils/functions.py
With this pull request the functions used for the combined analysis are refactored by following suggestions of flake8, isort and black. Any reviews are very much appreciated.
> Refactor combined analysis functions

- magicctapipe/scripts/lst1_magic/config.yaml
- magicctapipe/scripts/lst1_magic/lst1_magic_event_coincidence.py
Here I refactored the coincidence script by following suggestions by flake8, and run isort and black. It's ready for reviews.
> Refactor event coincidence

- magicctapipe/scripts/lst1_magic/config.yaml
- magicctapipe/scripts/lst1_magic/lst1_magic_create_irf.py
This pull request just refactored the logger information display of the script lst1_magic_create_irf.py in order to check more clearly if you set correct settings or not.
> Refactor creating IRFs

- magicctapipe/io/io.py
when training RF instead of maximum offset value minimum was shown instead
> fixed misleading message

- magicctapipe/scripts/lst1_magic/config.yaml
Modified default 2 values in the config file
> two corrected input values in the config file

- .gitignore
- .readthedocs.yaml
- docs/Makefile
- docs/requirements.txt
- docs/source/conf.py
- docs/source/index.rst
- docs/source/usage.rst
Initialize stuff for documentation.
> Start documentation

- docs/source/usage.rst
> Fix usage docs page.

- README.md
Fix URLs to ctapipe doc in README.
> Fix URLs to ctapipe docs

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
Add deploy to PyPI when a new tag like `v*` is created.
> Add deploy workflow

- .github/release-drafter.yml
- .github/workflows/release_drafter.yml
> Add release drafter action.

- .gitignore
- docs/_templates/autosummary/base.rst
- docs/_templates/autosummary/class.rst
- docs/_templates/autosummary/module.rst
- docs/api-reference/image/index.rst
- docs/api-reference/index.rst
- docs/api-reference/io/index.rst
- docs/api-reference/irfs/index.rst
- docs/api-reference/reco/index.rst
- docs/api-reference/utils/index.rst
- docs/conf.py
- docs/index.rst
- magicctapipe/io/io.py
- magicctapipe/irfs/utils.py
- magicctapipe/utils/__init__.py
- magicctapipe/utils/tels.py
- magicctapipe/utils/utils.py
Add API references in the documentation. For the moment, I do not care about the correctness of the documentation. That can go in another PR (maybe the same for ctapipe v0.19).
> API documentation

- docs/conf.py
- magicctapipe/image/calib.py
- magicctapipe/image/cleaning.py
- magicctapipe/image/leakage.py
- magicctapipe/io/gadf.py
- magicctapipe/io/io.py
- magicctapipe/irfs/utils.py
- magicctapipe/reco/__init__.py
- magicctapipe/reco/classifier_utils.py
- magicctapipe/reco/event_processing.py
- magicctapipe/reco/global_utils.py
- magicctapipe/reco/stereo.py
- magicctapipe/utils/badpixels.py
- magicctapipe/utils/camera_geometry.py
- magicctapipe/utils/filedir.py
- magicctapipe/utils/functions.py
- magicctapipe/utils/gti.py
- magicctapipe/utils/utils.py
As per title, this PR fixes the link to external repositories (e.g. for return types).
> Fix external links in the documentation

- .github/release-drafter.yml
- .github/workflows/ci.yml
- docs/developer-guide/pull-requests.rst
> Run only documentation job if "documentation-only" label on PR.

- magicctapipe/io/gadf.py
- magicctapipe/io/io.py
- magicctapipe/io/tests/test_io.py
- magicctapipe/io/tests/test_io_monly.py
- magicctapipe/scripts/lst1_magic/lst1_magic_dl1_stereo_to_dl2.py
- magicctapipe/scripts/lst1_magic/magic_calib_to_dl1.py
@jsitarek Here I put all the combo type dictionaries in the newest form (last: MAGICS)
> fixed combo_type bug

- .pre-commit-config.yaml
- MANIFEST.in
- docs/requirements.txt
- setup.cfg
> Fix description for pypi

- magicctapipe/scripts/lst1_magic/magic_calib_to_dl1.py
This addresses points 1 and 2 of #191.
> Write MAGIC-only subarray

- magicctapipe/scripts/lst1_magic/magic_calib_to_dl1.py
> Simplify reassignment of tel_ids.

- magicctapipe/io/io.py
> Drop NaN events also in MCs when loading DL2 data.

- magicctapipe/conftest.py
- magicctapipe/io/tests/test_io.py
Added a test to check if load_dl1_data_files can read 0.9 files
> test lstchain 0.9 files

- notebooks/check_signal_from_dl2.ipynb
Fixed function get_stereo_events in notebooks (fixed as get_stereo_events_old, until merging of next upgrades)
> get_stereo_events notebook

- magicctapipe/scripts/lst1_magic/semi_automatic_scripts/coincident_events.py
- magicctapipe/scripts/lst1_magic/semi_automatic_scripts/job_accounting.py
similar error logging as for the rest of the automatization scripts
> Auto mcp coincidence

- magicctapipe/scripts/lst1_magic/semi_automatic_scripts/job_accounting.py
- magicctapipe/scripts/lst1_magic/semi_automatic_scripts/stereo_events.py
renaming of the stereo output directories
> Auto mcp stereo

- magicctapipe/scripts/lst1_magic/semi_automatic_scripts/job_accounting.py
(since it is now used in setting up script)
> added list_cal.txt to the list of input files

- magicctapipe/scripts/lst1_magic/config.yaml
- magicctapipe/scripts/lst1_magic/lst1_magic_event_coincidence.py
- magicctapipe/scripts/lst1_magic/lst1_magic_stereo_reco.py
- magicctapipe/scripts/lst1_magic/magic_calib_to_dl1.py
- magicctapipe/scripts/lst1_magic/merge_hdf_files.py
(up to stereo reconstruction level)
> Possibility to store images 

- README.rst
- docs/_static/switcher.json
- docs/index.rst
PR to prepare release v0.4.2 from the master branch.
> Release v0.4.2

- magicctapipe/resources/database_config.yaml
- magicctapipe/scripts/lst1_magic/semi_automatic_scripts/database_production/update_MAGIC_database.py
Added new script (update_MAGIC_database.py) for automatically updating the MAGIC database.
> Auto update MAGIC database

- magicctapipe/scripts/lst1_magic/lst1_magic_event_coincidence.py
- magicctapipe/utils/__init__.py
- magicctapipe/utils/error_codes.py
exit code no coincident events
> Exit coinc

- magicctapipe/scripts/lst1_magic/semi_automatic_scripts/list_from_h5.py
Fix issue in LST db query (mixed bool & string format for MAGIC_stereo)
> fix list_from_h5 issue

- magicctapipe/resources/database_config.yaml
- magicctapipe/scripts/lst1_magic/semi_automatic_scripts/config_auto_MCP.yaml
- magicctapipe/scripts/lst1_magic/semi_automatic_scripts/dl1_production.py
- magicctapipe/scripts/lst1_magic/semi_automatic_scripts/list_from_h5.py
- magicctapipe/scripts/lst1_magic/semi_automatic_scripts/merging_runs.py
This branch enables data analysis using LST-1 together with only one MAGIC telescope. It will be useful in cases when one of the MAGIC telescopes is not operational (e.g., due to a failure).
> Adding the ability to perform LST-1 + one MAGIC analysis.

- magicctapipe/resources/config.yaml
- magicctapipe/scripts/lst1_magic/lst1_magic_cloud_profile_estimator.py
This script uses geometrical model [(article)](https://doi.org/10.1016/j.jheap.2024.03.003) for the estimation of the vertical transmission, base height and thickness of a cloud, the so-called "proton" LIDAR.
> Implementation of the cloud profile estimator in magic-cta-pipe

- magicctapipe/scripts/lst1_magic/semi_automatic_scripts/database_production/create_LST_table.py
- magicctapipe/scripts/lst1_magic/semi_automatic_scripts/database_production/nsb_to_h5.py
- magicctapipe/scripts/lst1_magic/semi_automatic_scripts/list_from_h5.py
Add a query on perfect match time (added to LST db) and fixed query on string/bool (MAGIC_stereo)
> Match time query

- magicctapipe/scripts/lst1_magic/semi_automatic_scripts/DL1_to_DL2.py
- magicctapipe/scripts/lst1_magic/semi_automatic_scripts/DL2_to_DL3.py
- magicctapipe/scripts/lst1_magic/semi_automatic_scripts/coincident_events.py
- magicctapipe/scripts/lst1_magic/semi_automatic_scripts/job_accounting.py
> Bug fix 0.5.5
